import ToggleColorMode from "./ToggleColorMode";
import "../globals.css";
import { Roboto } from "next/font/google";
import Navigation from "./Navigation";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

export const roboto = Roboto({
    weight: ["300", "400", "500", "700"],
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const MainContainer = ({ children }) => {
    return (
        // <html lang="en">
        //     <body className={roboto.className}>
        <ToggleColorMode>
            <Navigation />
            <AppRouterCacheProvider options={{ enableCssLayer: true }}>{children}</AppRouterCacheProvider>
        </ToggleColorMode>
        // </body>
        // </html>
    );
}

export default MainContainer;
