import ToggleColorMode, { ColorModeContext } from "./ToggleColorMode";
import "../../globals.css";
import { DM_Sans } from "next/font/google";
import Navigation from "./Navigation";


export const fontDMSans = DM_Sans({
    weight: ["300", "400", "500", "700"],
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const SharedLayout = ({ children }) => {
    return (

        <ColorModeContext.Consumer>
            {({ mode, handleToggleColorMode }) => (
                <ToggleColorMode mode={mode} handleToggleColorMode={handleToggleColorMode}>
                    <Navigation />
                    {children}
                </ToggleColorMode>
            )}
        </ColorModeContext.Consumer>
    );
}

export default SharedLayout;
